app/users/routes.py
import os
import secrets
from flask import json, url_for, redirect, Markup, Response, render_template, flash, g, session, jsonify, request, send_from_directory, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from app         import bcrypt, login_manager, db
from app.models    import User
from app.users.forms     import LoginForm, RegisterForm
import os, shutil, re, cgi, json

users = Blueprint('users', __name__)

# provide login manager with load_user callback
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# authenticate user
@users.route('/logout.html')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


# register user
@users.route('/register.html', methods=['GET', 'POST'])
def register():
    
    # define login form here
    form = RegisterForm(request.form)

    msg = None

    # custommize your pate title / description here
    title       = 'Register an account - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # check if both http method is POST and form is valid on submit
    if form.validate_on_submit():

        # assign form data to variables
        username = request.form.get('username', '', type=str)
        password = request.form.get('password', '', type=str) 
        name     = request.form.get('name'    , '', type=str) 
        email    = request.form.get('email'   , '', type=str) 

        # filter User out of database through username
        user = User.query.filter_by(user=username).first()

        # filter User out of database through username
        user_by_email = User.query.filter_by(email=email).first()

        if user:
            msg = 'Username exists!'
        
        elif user_by_email:
            msg = 'The emaill entered already has an account. Choose another one.'
        
        else:                    
            pw_hash = bcrypt.generate_password_hash(password)

            user = User(username, pw_hash, name, email)

            user.save()

            msg = flash('Your account has been created. You can now login.', 'success')
            return redirect(url_for('users.login'))

    # try to match the pages defined in -> themes/light-bootstrap/pages/
    return render_template('layouts/default.html',
                            title=title,
                            content=render_template( 'pages/register.html', 
                                                     form=form,
                                                     msg=msg))


# App main route + generic routing
@users.route('/', methods=['GET', 'POST'], defaults={'path': 'login.html'})
@users.route('/<path>')
def login(path):
    # define login form here
    form = LoginForm(request.form)
    # Flask message injected into the page, in case of any errors
    msg = None
    # custommize your page title / description here
    page_title = 'Login - ipNX vCPE'
    page_description = 'Online ipNX virtual Customer Premises Equipment.'
    # check if both http method is POST and form is valid on submit
    if form.validate_on_submit():
        # assign form data to variables
        username = request.form.get('username', '', type=str)
        password = request.form.get('password', '', type=str)
        # filter User out of database through username
        user = User.query.filter_by(user=username).first()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('main.index'))
            else:
                msg = "Wrong password. Please try again."
        else:
            msg = "Unknown user. Check again and re-enter."
    # try to match the pages defined in -> themes/light-bootstrap/pages/
    return render_template( 'layouts/logindefault.html',
                            title=page_title,
                            content=render_template( 'pages/'+path, form=form,
                                                    msg=msg) )

app/templates/pages/DHCP.html
      <div class="content">
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">DHCP stuff</h4>
              </div>
              <div class="card-body">
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              
            </div>
          </div>
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="places-buttons">
                  <div class="row">
                    <div class="col-md-6 ml-auto mr-auto text-center">
                      <h4 class="card-title">
                        DHCP cool pop ups
                        <p class="category">Click to view some pop ups</p>
                      </h4>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto">
                      <div class="row">
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','left')">Top Left</button>
                        </div>
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','center')">Top Center</button>
                        </div>
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('top','right')">Top Right</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-8 ml-auto mr-auto">
                      <div class="row">
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','left')">Bottom Left</button>
                        </div>
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','center')">Bottom Center</button>
                        </div>
                        <div class="col-md-4">
                          <button class="btn btn-primary btn-block" onclick="demo.showNotification('bottom','right')">Bottom Right</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/templates/pages/DNS.html
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header">
                <h4 class="card-title">DNS Server</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                      <tr>
                        <th>
                          ServerName
                        </th>
                        <th>
                          ServerCenter
                        </th>
                        <th>
                          SercerContent
                        </th>
                        <th class="text-center">
                          ServerStrength
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          ipNX
                        </td>
                        <td>
                          ipNX Nigeria Limited, VI
                        </td>
                        <td>
                          Broadband
                        </td>
                        <td class="text-center">
                          Excellent
                        </td>
                      </tr>
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="card  card-plain">
              
            </div>
          </div>
        </div>
      </div>

app/templates/pages/device.html
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header mb-5">
                <h5 class="card-category">Device Listings</h5>
              </div>
              <div class="card-body">
              </div>
            </div>
          </div>
        </div>
      </div>
      

app/templates/pages/index.html
      <!-- End Navbar -->
      <div class="content">
        <div class="row">
          <div class="col-12">
            <div class="card card-chart">
              <div class="card-header ">
                <div class="row">
                  <div class="col-sm-6 text-left">
                    <h5 class="card-category">WAN</h5>
                    <h2 class="card-title">Performance</h2>
                  </div>
                  <div class="col-sm-6">
                    <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                      <label class="btn btn-sm btn-primary btn-simple" id="1">
                        <input type="radio" class="d-none d-sm-none" name="options">
                        <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Purchases</span>
                        <span class="d-block d-sm-none">
                          <i class="tim-icons icon-gift-2"></i>
                        </span>
                      </label>
                      <label class="btn btn-sm btn-primary btn-simple" id="2">
                        <input type="radio" class="d-none" name="options">
                        <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Sessions</span>
                        <span class="d-block d-sm-none">
                          <i class="tim-icons icon-tap-02"></i>
                        </span>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="chart-area">
                  <canvas id="chartBig1"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="card card-chart">
              <div class="card-header">
                <h5 class="card-category">LAN</h5>
                <h3 class="card-title"><i class="tim-icons icon-bell-55 text-primary"></i> ipv4</h3>
              </div>
              <div class="card-body">
                <div class="chart-area">
                  <canvas id="chartLinePurple"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
          <div class="row"></div>
      </div>

app/templates/pages/login.html
<div class="content">
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <span class="ipnx"><img src="{{ url_for('static', filename='assets/img/logo.png') }}" alt="ipNX logo" /></span>
                    <h5 class="title">Login</h5>
                    {% if msg %}
                    <h6 class="subtitle">{{ msg | safe }}</h6>
                    {% else %}
                    <h6 class="subtitle">Sign in with your credentials</h6>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form role="form" method="post" action="">
                        {{ form.hidden_tag() }}
                        <div class="row">
                            <div class="col-md-1 px-md-1"></div>
                            <div class="col-md-1 px-md-1">
                                <!-- <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>-->
                            </div>
                            <div class="col-md-5 px-md-1">
                                <div class="form-group">
                                    {{ form.username(placeholder="Username",class="form-control") }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1 px-md-1"></div>
                            <div class="col-md-1 px-md-1">
                                <!--<div class="form-group">
                          <i class="fas fa-lock"></i>
                      </div>-->
                            </div>
                            <div class="col-md-5 px-md-1">
                                <div class="form-group">
                                    {{ form.password(placeholder="Password",class="form-control",type="password") }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1 px-md-1"></div>
                            <div class="col-md-1 px-md-1">
                                <button type="submit" class="btn btn-fill btn-primary">Log in</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    No account? Please <a href="{{ url_for('users.register') }}">register</a>
                </div>
            </div>
        </div>
    </div>

app/templates/pages/register.html
      <div class="content">
        <div class="row">
          <div class="col-md-10">
            <div class="card">
              <div class="card-header">
                <h5 class="title">Register</h5>

                    {% if msg %}
                      <label>{{ msg | safe }}</label>
                    {% else %}
                      <label>Please add your registration information</label>
                    {% endif %}

              </div>
              <div class="card-body">

              <form role="form" method="post" action="">

                  {{ form.hidden_tag() }}

                  <div class="row">

                    <div class="col-md-1 px-md-1"></div>

                    <div class="col-md-3 px-md-1">
                      <div class="form-group">
                        <label>Friendly Name (e.g. John Doe)</label>
                      </div>
                    </div>

                    <div class="col-md-5 px-md-1">
                      <div class="form-group">
                        {{ form.name(placeholder="Friendly Name",class="form-control") }}
                      </div>
                    </div>

                  </div>

                  <div class="row">

                    <div class="col-md-1 px-md-1"></div>

                    <div class="col-md-3 px-md-1">
                      <div class="form-group">
                        <label>Username</label>
                      </div>
                    </div>

                    <div class="col-md-5 px-md-1">
                      <div class="form-group">
                        {{ form.username(placeholder="Username",class="form-control") }}
                      </div>
                    </div>

                  </div>

                  <div class="row">

                    <div class="col-md-1 px-md-1"></div>

                    <div class="col-md-3 px-md-1">
                      <div class="form-group">
                        <label>Email</label>
                      </div>
                    </div>

                    <div class="col-md-5 px-md-1">
                      <div class="form-group">
                        {{ form.email(placeholder="eMail Address",class="form-control") }}
                      </div>
                    </div>

                  </div>

                  <div class="row">

                    <div class="col-md-1 px-md-1"></div>

                    <div class="col-md-3 px-md-1">
                      <div class="form-group">
                        <label>Password</label>
                      </div>
                    </div>

                    <div class="col-md-5 px-md-1">
                      <div class="form-group">
                        {{ form.password(placeholder="Password",class="form-control",type="password") }}
                      </div>
                    </div>

                  </div>

                  <div class="row">
                    <div class="col-md-1 px-md-1"></div>
                    <div class="col-md-1 px-md-1">

                    <button type="submit" class="btn btn-fill btn-primary">register</button>
                    </div>
                  </div>

                </form>
              </div>
              <div class="card-footer">
                Have already an account? Please <a href="{{ url_for('users.login') }}">login</a>
              </div>
            </div>
          </div>

        </div>
      </div>

app/templates/pages/wifi.html
<div class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">WiFi Stuff</h5>
                </div>
                <div class="card-body">

                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">Save</button>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</div>