app/main/routes.py
from flask import url_for, render_template, request, Blueprint, Response, jsonify
from flask_login import current_user, login_required
from app.models import User
import os, shutil, re, cgi, json, random, time
from datetime import datetime
main = Blueprint('main', __name__)


# authenticate user
@main.route('/index.html')
@login_required
def index():
    
    content = None
    
    try:
        # try to match the pages defined in -> themes/light-bootstrap/pages/
        return render_template('layouts/default.html',
                                content=render_template( 'pages/index.html') )
    except:
        abort(404)
    
# Used only for static export
@main.route('/wifi.html')
@login_required
def wifi():

    # custommize your page title / description here
    title = 'wifi settings - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # try to match the pages defined in -> pages/
    return render_template('layouts/default.html',
                            content=render_template( 'pages/wifi.html') )


# Used only for static export
@main.route('/DNS.html')
@login_required
def DNS():

    # custommize your page title / description here
    title = 'DNS servers - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # try to match the pages defined in -> pages/
    return render_template('layouts/default.html',
                            content=render_template( 'pages/DNS.html') )

# Used only for static export
@main.route('/DHCP.html')
@login_required
def DHCP():

    # custommize your page title / description here
    title = 'DHCP - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # try to match the pages defined in -> pages/
    return render_template('layouts/default.html',
                            content=render_template( 'pages/DHCP.html') )

# Used only for static export
@main.route('/device.html')
@login_required
def device():

    # custommize your page title / description here
    title = 'Device settings - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # try to match the pages defined in -> pages/
    return render_template('layouts/default.html',
                            content=render_template( 'pages/device.html') )

app/users/routes.py
import os
import secrets
from flask import json, url_for, redirect, Markup, Response, render_template, flash, g, session, jsonify, request, send_from_directory, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from app         import bcrypt, login_manager, db
from app.models    import User
from app.users.forms     import LoginForm, RegisterForm
import os, shutil, re, cgi, json

users = Blueprint('users', __name__)

# provide login manager with load_user callback
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# authenticate user
@users.route('/logout.html')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


# register user
@users.route('/register.html', methods=['GET', 'POST'])
def register():
    
    # define login form here
    form = RegisterForm(request.form)

    msg = None

    # custommize your pate title / description here
    title       = 'Register an account - ipNX vCPE'
    description = 'Online ipNX virtual Customer Premises Equipment.'

    # check if both http method is POST and form is valid on submit
    if form.validate_on_submit():

        # assign form data to variables
        username = request.form.get('username', '', type=str)
        password = request.form.get('password', '', type=str) 
        name     = request.form.get('name'    , '', type=str) 
        email    = request.form.get('email'   , '', type=str) 

        # filter User out of database through username
        user = User.query.filter_by(user=username).first()

        # filter User out of database through username
        user_by_email = User.query.filter_by(email=email).first()

        if user:
            msg = 'Username exists!'
        
        elif user_by_email:
            msg = 'The emaill entered already has an account. Choose another one.'
        
        else:                    
            pw_hash = bcrypt.generate_password_hash(password)

            user = User(username, pw_hash, name, email)

            user.save()

            msg = flash('Your account has been created. You can now login.', 'success')
            return redirect(url_for('users.login'))

    # try to match the pages defined in -> themes/light-bootstrap/pages/
    return render_template('layouts/default.html',
                            title=title,
                            content=render_template( 'pages/register.html', 
                                                     form=form,
                                                     msg=msg))


# App main route + generic routing
@users.route('/', methods=['GET', 'POST'], defaults={'path': 'login.html'})
@users.route('/<path>')
def login(path):
    # define login form here
    form = LoginForm(request.form)
    # Flask message injected into the page, in case of any errors
    msg = None
    # custommize your page title / description here
    page_title = 'Login - ipNX vCPE'
    page_description = 'Online ipNX virtual Customer Premises Equipment.'
    # check if both http method is POST and form is valid on submit
    if form.validate_on_submit():
        # assign form data to variables
        username = request.form.get('username', '', type=str)
        password = request.form.get('password', '', type=str)
        # filter User out of database through username
        user = User.query.filter_by(user=username).first()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('main.index'))
            else:
                msg = "Wrong password. Please try again."
        else:
            msg = "Unknown user. Check again and re-enter."
    # try to match the pages defined in -> themes/light-bootstrap/pages/
    return render_template( 'layouts/logindefault.html',
                            title=page_title,
                            content=render_template( 'pages/'+path, form=form,
                                                    msg=msg) )

app/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
        <li class="button-container">
          <a href="https://www.creative-tim.com/product/black-dashboard" target="_blank" class="btn btn-primary btn-block btn-round">Download Now</a>
          <a href="https://demos.creative-tim.com/black-dashboard/docs/1.0/getting-started/introduction.html" target="_blank" class="btn btn-default btn-block btn-round">
            Documentation
          </a>
        </li>
        <li class="header-title">Thank you for 95 shares!</li>
        <li class="button-container text-center">
          <button id="twitter" class="btn btn-round btn-info"><i class="fab fa-twitter"></i> &middot; 45</button>
          <button id="facebook" class="btn btn-round btn-info"><i class="fab fa-facebook-f"></i> &middot; 50</button>
          <br>
          <br>
          <a class="github-button" href="https://github.com/creativetimofficial/black-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star ntkme/github-buttons on GitHub">Star</a>
        </li>
      </ul>
    </div>
  </div>

app/templates/includes/footer.html
     <footer class="footer">
        <div class="container-fluid">
          <div class="copyright" id="copyright">
            &copy;
            <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, by <a href="#" target="_blank">Idogun John</a>, 
            Coded in <a href="http://flask.pocoo.org/">Flask</a> by <a href="#">Sirjon</a>
          </div>
        </div>
      </footer>

app/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <img src="{{ url_for('static', filename='assets/img/logo.png') }}" class="dashlogo" />
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto">
              <li class="search-bar input-group">
                <a href="{{url_for('main.index')}}"><button style="border: purple solid" class="btn btn-link button-fill-right ">Main</button></a>
              </li>
                <li>
                    <a href="{{ url_for('users.logout') }}"><button style="border: purple solid" class="btn btn-link button-fill-right ">Log out</button></a>
                </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      

app/templates/includes/sidenav.html
    <div class="sidebar">
      <!-- Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red" -->
      <div class="sidebar-wrapper">
        <div class="logo">
          <a href="{{ url_for('main.index') }}" class="simple-text logo-mini">
            <i class="fas fa-globe fa-2x"></i>
          </a>
          <a href="#" class="simple-text logo-normal">
            settings
          </a>
        </div>
        <ul class="nav">
          <li class="">
            <a href="{{ url_for('main.DHCP') }}">
              <i class="fas fa-toggle-on fa-5x"></i>
              <p>DHCP modification</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.wifi') }}">
              <i class="fas fa-wifi fa-5x"></i>
              <p>wifi settings</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.DNS') }}">
              <i class="fas fa-server fa-5x"></i>
              <p>DNS servers</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('main.device') }}">
              <i class="fas fa-laptop fa-5x"></i>
              <p>Device settings</p>
            </a>
          </li>
        </ul>
      </div>
    </div>